// <auto-generated />
using System;
using DataAccess.Concrete;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230707211550_suggestions_update")]
    partial class suggestions_update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Concrete.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnnouncementTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("Entities.Concrete.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConfirmCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParentName_Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissionRights")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("School")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("RoomId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Entities.Concrete.EventParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("StudentId");

                    b.ToTable("EventParticipant");
                });

            modelBuilder.Entity("Entities.Concrete.MonthsForPay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ExpiresDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Months");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 750m,
                            ExpiresDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "September"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 1500m,
                            ExpiresDate = new DateTime(2023, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "October"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 1500m,
                            ExpiresDate = new DateTime(2023, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "November"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 1500m,
                            ExpiresDate = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "December"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 1500m,
                            ExpiresDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "January"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 1500m,
                            ExpiresDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "February"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 1500m,
                            ExpiresDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "March"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 1500m,
                            ExpiresDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "April"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 1500m,
                            ExpiresDate = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "May"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 750m,
                            ExpiresDate = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Month = "June"
                        });
                });

            modelBuilder.Entity("Entities.Concrete.PaymentRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonthId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.HasIndex("StudentId");

                    b.ToTable("PaymentRecord");
                });

            modelBuilder.Entity("Entities.Concrete.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DateOfEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("Entities.Concrete.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Availability")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfStudents")
                        .HasColumnType("int");

                    b.Property<int>("Quota")
                        .HasColumnType("int");

                    b.Property<int>("RoomNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 101
                        },
                        new
                        {
                            Id = 102,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 102
                        },
                        new
                        {
                            Id = 103,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 103
                        },
                        new
                        {
                            Id = 104,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 104
                        },
                        new
                        {
                            Id = 105,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 105
                        },
                        new
                        {
                            Id = 106,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 106
                        },
                        new
                        {
                            Id = 107,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 107
                        },
                        new
                        {
                            Id = 108,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 108
                        },
                        new
                        {
                            Id = 109,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 109
                        },
                        new
                        {
                            Id = 110,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 110
                        },
                        new
                        {
                            Id = 111,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 111
                        },
                        new
                        {
                            Id = 112,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 112
                        },
                        new
                        {
                            Id = 113,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 113
                        },
                        new
                        {
                            Id = 114,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 114
                        },
                        new
                        {
                            Id = 115,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 115
                        },
                        new
                        {
                            Id = 116,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 116
                        },
                        new
                        {
                            Id = 117,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 117
                        },
                        new
                        {
                            Id = 118,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 118
                        },
                        new
                        {
                            Id = 119,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 119
                        },
                        new
                        {
                            Id = 120,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 120
                        },
                        new
                        {
                            Id = 202,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 202
                        },
                        new
                        {
                            Id = 203,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 203
                        },
                        new
                        {
                            Id = 204,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 204
                        },
                        new
                        {
                            Id = 205,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 205
                        },
                        new
                        {
                            Id = 206,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 206
                        },
                        new
                        {
                            Id = 207,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 207
                        },
                        new
                        {
                            Id = 208,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 208
                        },
                        new
                        {
                            Id = 209,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 209
                        },
                        new
                        {
                            Id = 210,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 210
                        },
                        new
                        {
                            Id = 211,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 211
                        },
                        new
                        {
                            Id = 212,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 212
                        },
                        new
                        {
                            Id = 213,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 213
                        },
                        new
                        {
                            Id = 214,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 214
                        },
                        new
                        {
                            Id = 215,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 215
                        },
                        new
                        {
                            Id = 216,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 216
                        },
                        new
                        {
                            Id = 217,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 217
                        },
                        new
                        {
                            Id = 218,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 218
                        },
                        new
                        {
                            Id = 219,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 219
                        },
                        new
                        {
                            Id = 220,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 220
                        },
                        new
                        {
                            Id = 302,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 302
                        },
                        new
                        {
                            Id = 303,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 303
                        },
                        new
                        {
                            Id = 304,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 304
                        },
                        new
                        {
                            Id = 305,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 305
                        },
                        new
                        {
                            Id = 306,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 306
                        },
                        new
                        {
                            Id = 307,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 307
                        },
                        new
                        {
                            Id = 308,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 308
                        },
                        new
                        {
                            Id = 309,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 309
                        },
                        new
                        {
                            Id = 310,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 310
                        },
                        new
                        {
                            Id = 311,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 311
                        },
                        new
                        {
                            Id = 312,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 312
                        },
                        new
                        {
                            Id = 313,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 313
                        },
                        new
                        {
                            Id = 314,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 314
                        },
                        new
                        {
                            Id = 315,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 315
                        },
                        new
                        {
                            Id = 316,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 316
                        },
                        new
                        {
                            Id = 317,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 317
                        },
                        new
                        {
                            Id = 318,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 318
                        },
                        new
                        {
                            Id = 319,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 319
                        },
                        new
                        {
                            Id = 320,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 320
                        },
                        new
                        {
                            Id = 402,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 402
                        },
                        new
                        {
                            Id = 403,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 403
                        },
                        new
                        {
                            Id = 404,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 404
                        },
                        new
                        {
                            Id = 405,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 405
                        },
                        new
                        {
                            Id = 406,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 406
                        },
                        new
                        {
                            Id = 407,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 407
                        },
                        new
                        {
                            Id = 408,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 408
                        },
                        new
                        {
                            Id = 409,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 409
                        },
                        new
                        {
                            Id = 410,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 410
                        },
                        new
                        {
                            Id = 411,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 411
                        },
                        new
                        {
                            Id = 412,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 412
                        },
                        new
                        {
                            Id = 413,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 413
                        },
                        new
                        {
                            Id = 414,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 414
                        },
                        new
                        {
                            Id = 415,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 415
                        },
                        new
                        {
                            Id = 416,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 416
                        },
                        new
                        {
                            Id = 417,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 417
                        },
                        new
                        {
                            Id = 418,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 418
                        },
                        new
                        {
                            Id = 419,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 419
                        },
                        new
                        {
                            Id = 420,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 420
                        },
                        new
                        {
                            Id = 502,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 502
                        },
                        new
                        {
                            Id = 503,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 503
                        },
                        new
                        {
                            Id = 504,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 504
                        },
                        new
                        {
                            Id = 505,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 505
                        },
                        new
                        {
                            Id = 506,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 506
                        },
                        new
                        {
                            Id = 507,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 507
                        },
                        new
                        {
                            Id = 508,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 508
                        },
                        new
                        {
                            Id = 509,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 509
                        },
                        new
                        {
                            Id = 510,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 510
                        },
                        new
                        {
                            Id = 511,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 511
                        },
                        new
                        {
                            Id = 512,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 512
                        },
                        new
                        {
                            Id = 513,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 513
                        },
                        new
                        {
                            Id = 514,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 514
                        },
                        new
                        {
                            Id = 515,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 515
                        },
                        new
                        {
                            Id = 516,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 516
                        },
                        new
                        {
                            Id = 517,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 517
                        },
                        new
                        {
                            Id = 518,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 518
                        },
                        new
                        {
                            Id = 519,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 519
                        },
                        new
                        {
                            Id = 520,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 520
                        },
                        new
                        {
                            Id = 602,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 602
                        },
                        new
                        {
                            Id = 603,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 603
                        },
                        new
                        {
                            Id = 604,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 604
                        },
                        new
                        {
                            Id = 605,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 605
                        },
                        new
                        {
                            Id = 606,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 606
                        },
                        new
                        {
                            Id = 607,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 607
                        },
                        new
                        {
                            Id = 608,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 608
                        },
                        new
                        {
                            Id = 609,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 609
                        },
                        new
                        {
                            Id = 610,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 610
                        },
                        new
                        {
                            Id = 611,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 611
                        },
                        new
                        {
                            Id = 612,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 612
                        },
                        new
                        {
                            Id = 613,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 613
                        },
                        new
                        {
                            Id = 614,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 614
                        },
                        new
                        {
                            Id = 615,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 615
                        },
                        new
                        {
                            Id = 616,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 616
                        },
                        new
                        {
                            Id = 617,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 617
                        },
                        new
                        {
                            Id = 618,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 618
                        },
                        new
                        {
                            Id = 619,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 619
                        },
                        new
                        {
                            Id = 620,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 620
                        },
                        new
                        {
                            Id = 702,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 702
                        },
                        new
                        {
                            Id = 703,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 703
                        },
                        new
                        {
                            Id = 704,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 704
                        },
                        new
                        {
                            Id = 705,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 705
                        },
                        new
                        {
                            Id = 706,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 706
                        },
                        new
                        {
                            Id = 707,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 707
                        },
                        new
                        {
                            Id = 708,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 708
                        },
                        new
                        {
                            Id = 709,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 709
                        },
                        new
                        {
                            Id = 710,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 710
                        },
                        new
                        {
                            Id = 711,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 711
                        },
                        new
                        {
                            Id = 712,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 712
                        },
                        new
                        {
                            Id = 713,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 713
                        },
                        new
                        {
                            Id = 714,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 714
                        },
                        new
                        {
                            Id = 715,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 715
                        },
                        new
                        {
                            Id = 716,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 716
                        },
                        new
                        {
                            Id = 717,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 717
                        },
                        new
                        {
                            Id = 718,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 718
                        },
                        new
                        {
                            Id = 719,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 719
                        },
                        new
                        {
                            Id = 720,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 720
                        },
                        new
                        {
                            Id = 802,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 802
                        },
                        new
                        {
                            Id = 803,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 803
                        },
                        new
                        {
                            Id = 804,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 804
                        },
                        new
                        {
                            Id = 805,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 805
                        },
                        new
                        {
                            Id = 806,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 806
                        },
                        new
                        {
                            Id = 807,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 807
                        },
                        new
                        {
                            Id = 808,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 808
                        },
                        new
                        {
                            Id = 809,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 809
                        },
                        new
                        {
                            Id = 810,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 810
                        },
                        new
                        {
                            Id = 811,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 811
                        },
                        new
                        {
                            Id = 812,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 812
                        },
                        new
                        {
                            Id = 813,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 813
                        },
                        new
                        {
                            Id = 814,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 814
                        },
                        new
                        {
                            Id = 815,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 815
                        },
                        new
                        {
                            Id = 816,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 816
                        },
                        new
                        {
                            Id = 817,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 817
                        },
                        new
                        {
                            Id = 818,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 818
                        },
                        new
                        {
                            Id = 819,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 4,
                            RoomNo = 819
                        },
                        new
                        {
                            Id = 820,
                            Availability = true,
                            NumberOfStudents = 0,
                            Quota = 7,
                            RoomNo = 820
                        });
                });

            modelBuilder.Entity("Entities.Concrete.Suggestion_Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("Suggestions_Complaints");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Concrete.AppUser", b =>
                {
                    b.HasOne("Entities.Concrete.Room", "Room")
                        .WithMany("Students")
                        .HasForeignKey("RoomId");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Entities.Concrete.EventParticipant", b =>
                {
                    b.HasOne("Entities.Concrete.Event", "Event")
                        .WithMany("Students")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.AppUser", "Student")
                        .WithMany("Events")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entities.Concrete.PaymentRecord", b =>
                {
                    b.HasOne("Entities.Concrete.MonthsForPay", "Month")
                        .WithMany("PaymentRecords")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.AppUser", "Student")
                        .WithMany("PaymentRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Month");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entities.Concrete.Permission", b =>
                {
                    b.HasOne("Entities.Concrete.AppUser", "Student")
                        .WithMany("Permissions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Entities.Concrete.Suggestion_Complaint", b =>
                {
                    b.HasOne("Entities.Concrete.AppUser", "Complainant_Recommender")
                        .WithMany("Suggestions_Complaints")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complainant_Recommender");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Entities.Concrete.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Entities.Concrete.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Concrete.AppUser", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("PaymentRecords");

                    b.Navigation("Permissions");

                    b.Navigation("Suggestions_Complaints");
                });

            modelBuilder.Entity("Entities.Concrete.Event", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entities.Concrete.MonthsForPay", b =>
                {
                    b.Navigation("PaymentRecords");
                });

            modelBuilder.Entity("Entities.Concrete.Room", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
